### ISSUE TITLE
为什么跑不起来呀

### ISSUE THREAD

**Issue by 451761830** [jiiiimmmmmmm/face_detect#1]
npm install 后在微信开发者工具里构建时报错
![image](https://user-images.githubusercontent.com/48461152/112091849-3d6e5a00-8bd1-11eb-8e82-61695e871a2c.png)

**Comment by shuxiongwuziqi** [comment]
可以提供具体一点的错误吗？我无法重现这个错误。

**Comment by shuxiongwuziqi** [comment]
我自己构建也出现了这个问题，但是好像不影响运行。

**Comment by shuxiongwuziqi** [comment]
hi,我重新完善了一下代码，又重复自己装了几次，虽然会报这个错误，但是确实不影响运行呢。我把快速安装的步骤放在readme了，你可以再试试。
